config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'pages/:id' => 'pages#showproduct', as: 'show_product'

  get '/products/new' => 'products#new', as: 'new_product'
  post '/products' => 'products#create'
  get '/products/user' => 'products#user', as: 'user_product'
  get '/products/:id/edit' => 'products#edit', as: 'product'
  patch '/products/:id/edit' => 'products#update'
  delete '/products/:id' => 'products#destroy', as: 'destroy_product'

  resources :products do
    resources :bookings
  end

  resources :chats
  resources :messages

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_one :chat

  after_create :create_chat

  def create_chat
    Chat.create(booking_id: self.id, name: "chat #{self.id}", booker: self.user.id, seller_id: self.product.user.id, new: true)
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :booking
  has_many :messages, dependent: :destroy

  after_create :create_first_message


  def create_first_message
    Message.create(chat_id: self.id, user_id: self.booker, content: "Hi, i have just booked your product")
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  after_create :change_message_new

  def change_message_new
   message = Message.find_by(id: self.id)
   message.update(new:true)
  end

  def self.turn_message_new_to_false(id)
    message = Message.find(id)
    message.update(new:false)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_one_attached :photo
  belongs_to :user
  has_one :booking

  include PgSearch::Model
  pg_search_scope :search_by_name_description,
    against: [ :name, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :products
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id).includes(:product)
  end

  def show

  end

  def new
    @product = Product.find(params[:product_id])
    @booking = Booking.new
  end

  def create
    @product = Product.find(params[:product_id])
    @booking = Booking.new(product_id: @product.id, user_id: current_user.id, paid:true)
    @booking.save
    redirect_to '/'
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def params_booking
    params.require(:booking).permit(:paid)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
   @bookings = Booking.all.includes(:product)
   @bookings.each do |b|
     @seller_id = b.product.user_id == current_user.id
   end
    @chats = Chat.where(booker: current_user.id).includes(:messages)
    .or(Chat.where(seller_id: current_user.id).includes(:messages))

  end

  def show
    @c = Chat.find(params[:id])
    @c.messages.each do |m|
      if m.new
        Message.turn_message_new_to_false(m.id)
      end
    end
    @chat = Chat.find(params[:id])
    if @chat.booker == current_user.id || @chat.seller_id == current_user.id
      @chat_messages = @chat.messages.includes(:user)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def new
  @message = Message.new()
end

def create
  @message = Message.new(params_message)
  @message.user_id = current_user.id
  @message.chat_id = params[:message][:chat_id]
  @message.save

  @bookings = Booking.all.includes(:product)
   @bookings.each do |b|
     @seller_id = b.product.user_id == current_user.id
   end
    @chats = Chat.where(booker: current_user.id).includes(:messages)
    .or(Chat.where(seller_id: current_user.id).includes(:messages))
  render "chats/index"
  # redirect_back(fallback_location: root_path)
end

private

def params_message
  params.require(:message).permit(:content, :user_id, :chat_id)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

    if params[:query].nil? or params[:query] == ""
      @products = Product.all
    else
      @products = Product.search_by_name_description(params[:query])


    end

    if current_user
      @user_chats = Chat.where(booker: current_user.id).includes(:messages)
      .or(Chat.where(seller_id: current_user.id).includes(:messages))

      @user_chats.any? do |c|
        @answer = c.messages.any? do |m|
          m.new && (m.user_id != current_user.id)
        end
      end
    end
  end

  def showproduct
    @product = Product.find(params[:id])
    if @product.user_id == current_user.id
      render action: 'showproduct' and return
    else
      render action: 'others_product'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    end

  def create
    @product = Product.new(params_product)
    @product.user = current_user
    @product.save
    if @product.user.seller == false
      @product.user.seller = true
      @product.user.save
    end
    redirect_to "/"
  end

  def user
    @user = current_user
    @products = Product.where(user_id: @user.id)

  end

  def edit
    @product = Product.find(params[:id])
      end

  def update
    @product = Product.find(params[:id])
        @product.update(params_product)
    redirect_to '/products/user'
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to '/products/user'

  end


  private

  def params_product
    params.require(:product).permit(:name, :price, :description, :photo)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="flex flex-column">
  <h1 class="text-center" style="margin-top:50px;margin-bottom:50px">My bookings history</h1>
  <% @bookings.each do |b| %>
  <div class="text-center booking-grid">
    <h3><%=b.product.name%></h3>
    <div style="display:flex;justify-content: center;align-items: center;padding-top:10px">
      <p style="margin-right:4rem">Total: <%=b.product.price%> rmb</p>
      <p>created: <%=time_ago_in_words(b.created_at)%></p>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container text-center" style="margin-top:20vh">
  <h1 class="text-center">New Booking</h1>
  <div style="margin-top:25px">
    <% time = Time.new %>
    <h4>Purchase date: <%=Date.today%></h4>
    <h4>Purchasing product name: <%=@product.name %></h4>
    <h4>Total: <%= @product.price%> rmb</h4>

    <%= form_for [@product,@booking] do |f| %>
    <%= f.submit "Pay",style:"margin-top:20px;text-decoration:none;color:white;background:rgb(0, 115, 188);border:none;padding-left:40px;padding-right:40px;padding-top:8px;padding-bottom:8px" %>
    <% end %>
  </div>
</div>

app/views/chats/index.html.erb
<div class="container" style="margin-top:30px">
  <h1 class="text-center">Chats list</h1>
</div>

<div class="container chats_div">
  <% @chats.each do |chat| %>
  <div class="list-group">
      <button type="button" class="list-group-item list-group-item-action" style="display:flex;justify-content: space-between;align-items:center">
        <%=link_to chat.name, chat_path(chat),class:'chats' ,style:"color:black", :data => { :ind => chat.id } %>
        <% chat.messages.each do |m| %>
          <% if m.new && (m.user_id != current_user.id) %>
            <div style="text-align: center;padding: 10px;">
              <%= image_tag "notification.png" , style:"height:20px;width:20px"%>
              <p class="show display" style="color:pink" data-number=<%=chat.id%> >new message</p>
            </div>
          <%end%>
        <% end %>
      </button>
  </div>
  <%end%>
</div>

app/views/chats/show.html.erb
<div class="container text-center" style="margin-bottom:20px;margin-top:50px">
  <h1>
    ChatRoom: <%= @chat.name %>
  </h1>
</div>

<div class="row">

  <div class="col">
    <div class="chat">
      <% @chat_messages.each do |chat_message| %>
        <div style="margin-bottom:10px;display:flex">
         <% if chat_message.user_id == current_user.id %>
            <div style="padding:20px;display:flex">
              <h3 style="border-radius:50%;background:rgb(22, 127, 251);height:50px;width:50px;padding-top:8px;padding-left:5px;margin-top:10px">Me</h3>
              <div style="margin-left:20px">
                <p>send: <%=time_ago_in_words(chat_message.created_at)%></p>
                <h5>"<%=chat_message.content%>"</h5>
              </div>
            </div>
         <% else %>
            <div style="padding:20px;display:flex">
              <h3 style="border-radius:50%;background:#fe8761;height:50px;width:50px;padding-top:8px;padding-left:8px;margin-top:10px">He</h3>
              <div style="margin-left:20px">
                <p>send: <%=time_ago_in_words(chat_message.created_at)%></p>
                <p>"<%= chat_message.content %>"</p>
              </div>
            </div>
         <%end %>
       </div>
      <% end %>
    </div>

      <%= form_for Message.new, :html => {:class => 'press'} do |f| %>
        <div class="input-group mb-3" style="display:flex;justify-content: center">
          <%= f.label "new message" %><br>
          <%= f.text_field :content,class: 'chat-input'%>
          <div class="input-group-append">
            <%= f.submit "Send", class: 'btn btn-primary chat-input button-blue' %>
          </div>
        </div>
        <%= f.hidden_field :chat_id,:value => @chat.id %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <h1 class="text-center" style="color:white;transform: translate(0px, 185px);text-shadow:1px 0px grey">Beyong your imaginations.</h1>
  <% if current_user && @answer%>
    <div class="round-notification">
      <%=image_tag "notification.png", class:"notification-icon" %>
      <p class="notification-text">You have new messages</p>
    </div>
  <%end%>
</div>
<h1 class="text-center main-header" style="margin-bottom:30px;margin-top:30px">On sell products</h1>
<div class="container">
  <div class="text-center">
    <%= form_for root_path , :method => 'get', :html => { :class => "search"} do |f| %>
      <%= f.text_field :query, 'name'=>'query' ,class:"input-field",style:"height:35px;border:none" %>
    <%= f.submit "search", style:"background: pink;
    border: none;
    color: white;
    padding-left: 25px;
    padding-right: 25px;
    padding-top: 5px;
    padding-bottom: 5px;" %>
    <% end %>
  </div>
  <div class="row">
    <% @products.each do |p| %>
    <div class="col custom-card" style="display:flex;flex-direction:column;margin:10px;">
      <%= link_to show_product_path(p.id) do %>
        <%= cl_image_tag p.photo, height: 300, width: 300, class:"image-link" %>
      <%end%>
      <div class="product-description">
        <p><%= link_to p.name, show_product_path(p.id),style:"color:#f8b500" %></p>
        <p style="color:#f8b500"><%= p.price %> rmb</p>
      </div>
      </div>
    <%end%>
    </div>
  </div>
</div>

app/views/pages/others_product.html.erb
<div class="container other-container">
  <div class="container image-flex">
    <%= cl_image_tag @product.photo, height: 400, width: 400 %>
  </div>
  <div class="container text-center" style="border:1px solid white;padding:50px">
    <h1 style="margin-bottom:30px"><%= @product.name%></h1>
    <p>seller name: <%= @product.user.name%></p>
    <p>sell price: <%= @product.price%> rmb</p>
    <p><%= @product.description %></p>
    <button style="background:rgb(0, 115, 188);border:none;padding-left:25px;padding-right:25px;padding-top:10px;padding-bottom:10px;margin-top:20px"><%=link_to "book now", new_product_booking_path(@product.id), style:"text-decoration:none;color:white;background:rgb(0, 115, 188)" %></button>
  </div>
</div>

app/views/pages/showproduct.html.erb
<div class="container show-container">
  <div class="container show-image">
    <%= cl_image_tag @product.photo, height: 400, width: 400 %>
  </div>

  <div class="container text-center" style="border:1px solid white;padding:50px">
    <div class="alert alert-warning" role="alert">
      Hi,it's your product ;)
    </div>
    <h1 style="margin-bottom:30px"><%= @product.name%></h1>
    <p>seller name: <%= @product.user.name%></p>
    <p>sell price: <%= @product.price%> rmb</p>
    <div style="margin-top:25px">
      <h3>Product description:</h3>
      <p><%= @product.description %></p>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container text-center edit-container">
  <h1 style="margin-bottom:35px">Edit product</h1>

  <%= form_for @product do |f| %>
    <%= f.label 'product name' %><br>
    <%= f.text_field :name ,class:"edit-input"%><br>

    <%= f.label 'product price' %><br>
    <%= f.text_field :price ,class:"edit-input" %><br>

    <%= f.label 'product description' %><br>
    <%= f.text_area :description ,class:"edit-input"%><br>

    <div>
      <%= f.file_field :photo , style:"margin-left:100px;margin-bottom:15px;"%>
      <%= f.hidden_field :photo_cache %>
    </div>
    <%= f.submit "Submit update", style:"color:white;margin-top:30px;background:rgb(0, 115, 188);border:none;padding-left:25px;padding-right:25px;padding-top:10px;padding-bottom:10px" %>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="container text-center form-container">
  <h1 style="margin-bottom:35px">Sell my Product </h1>

<%= form_for @product do |f| %>
  <%= f.label 'product name'%><br>
  <%= f.text_field :name , class:"input-field"%><br>

  <%= f.label 'product price'%><br>
  <%= f.text_field :price ,class:"input-field"%><br>

  <%= f.label 'product description'%><br>
  <%= f.text_area :description ,class:"input-field"%><br>
  <div>
  <%= f.file_field :photo , style:"margin-left:100px;margin-bottom:15px"%>
  <%= f.hidden_field :photo_cache, class:"text-center" %>
  </div>
  <%= f.submit "Submit update", style:"color:white;margin-top:30px;background:rgb(0, 115, 188);border:none;padding-left:25px;padding-right:25px;padding-top:10px;padding-bottom:10px" %>
  <% end %>

</div>

app/views/products/user.html.erb
<div class="container text-center width_50" style="margin-top:30px">
  <h1 style="margin-bottom:30px">My Dashboard</h1>
  <% @products.each do |p| %>
  <div class="flex margin_bottom white_border">
      <div>
        <%= cl_image_tag p.photo,height:300, width:300,:transformation => [{:radius => 'max'}] %>
      </div>
      <div class="width_100 pd">
        <div class="tc margin_bottom">
          <h4>Product name: <%= p.name %></h4>
          <h4> Price: <%= p.price %> rmb</h4>
        </div>
        <div class="tc">
          <%= link_to "Update", "/products/#{p.id}/edit", style:"text-decoration:none;color:white;background:rgb(0, 115, 188);padding:10px" %>
          <%=link_to "Delete", "/products/#{p.id}", :method => 'delete' , style:"text-decoration:none;color:white;background:red;padding:10px"%>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-login" style="font-size:10px" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" style="font-size:10px" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" ,style:"border-radius:50%;width:50px;height:50px"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sell new Product", '/products/new', class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Dashboard", '/products/user', class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "smiley.jpg", class: "avatar dropdown-toggle", style:"border-redius:50%;width:40px;height:40px", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "my bookings", "/products/:products_id/bookings", class: "dropdown-item" %>
            <%= link_to "Chats", chats_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>